In [2]:
import matplotlib
import pathlib
import mne

# import os
# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# from tqdm import tqdm
# import mne

In [3]:
# use this can show graph in new page!
# useful!
matplotlib.use('Qt5Agg')

NameError: name 'matplotlib' is not defined

In [45]:
# data_folder = mne.datasets.sample.data_path('OpenMIIR-RawEEG_v1')
# data_raw_file = os.path.join(data_folder, 'MEG', 'sample',
#                                     'P01-raw.fif')
fname = 'OpenMIIR-RawEEG_v1/P01-raw.fif'
raw = mne.io.read_raw_fif(fname, preload=True)
raw

Opening raw data file OpenMIIR-RawEEG_v1/P01-raw.fif...
Isotrak not found
    Read a total of 1 projection items:
        Average EEG reference (1 x 64)  idle
    Range : 0 ... 2478165 =      0.000 ...  4840.166 secs
Ready.
Reading 0 ... 2478165  =      0.000 ...  4840.166 secs...


<Raw | P01-raw.fif, 69 x 2478166 (4840.2 s), ~1.27 GB, data loaded>

In [22]:
raw.plot()

<MNEBrowseFigure size 3024x1654 with 5 Axes>

Channels marked as bad: ['P8', 'P10', 'T8']
Channels marked as bad: ['Fp1', 'F1', 'FC3', 'C1', 'FC1']


In [5]:
events = mne.find_events(raw) # 51 IDs

540 events found
Event IDs: [  11   12   13   14   21   22   23   24   31   32   33   34   41   42
   43   44  111  112  113  114  121  122  123  124  131  132  133  134
  141  142  143  144  211  212  213  214  221  222  223  224  231  232
  233  234  241  242  243  244 1000 1111 2000 2001]


In [19]:
for e in events:
  print(e)

[512   0 121]
[ 520    0 1000]
[8189    0  122]
[8195    0 1000]
[16564     0   123]
[21614     0  1111]
[21796     0  1000]
[25493     0    31]
[25498     0  1000]
[34435     0    32]
[34442     0  1000]
[43920     0    33]
[50080     0  1111]
[50218     0  1000]
[54015     0   231]
[54021     0  1000]
[62748     0   232]
[62754     0  1000]
[72011     0   233]
[77939     0  1111]
[78121     0  1000]
[81825     0   131]
[81831     0  1000]
[90292     0   132]
[90298     0  1000]
[99436     0   133]
[105253      0   1111]
[105434      0   1000]
[109195      0    141]
[109201      0   1000]
[119782      0    142]
[119788      0   1000]
[130922      0    143]
[138734      0   1111]
[138916      0   1000]
[142677      0    111]
[142683      0   1000]
[153528      0    112]
[153535      0   1000]
[164846      0    113]
[172830      0   1111]
[172977      0   1000]
[176766      0     11]
[176773      0   1000]
[187042      0     12]
[187048      0   1000]
[198054      0     13]
[205741     

In [7]:
raw.info

<Info | 10 non-empty values
 bads: []
 ch_names: Fp1, AF7, AF3, F1, F3, F5, F7, FT7, FC5, FC3, FC1, C1, C3, C5, ...
 chs: 64 EEG, 4 EOG, 1 Stimulus
 custom_ref_applied: False
 file_id: 4 items (dict)
 highpass: 0.0 Hz
 lowpass: 417.0 Hz
 meas_date: 2015-02-02 17:06:12 UTC
 meas_id: 4 items (dict)
 nchan: 69
 projs: Average EEG reference: off
 sfreq: 512.0 Hz
>

In [47]:
raw.plot()

<MNEBrowseFigure size 3024x1654 with 5 Axes>

Channels marked as bad: ['P8', 'P10', 'T8']


## Visualize the sensor locations

In [46]:
# raw.plot_sensors(ch_type='eeg')
raw.plot_sensors(show_names=True)

<Figure size 1280x1280 with 1 Axes>

In [10]:
raw.plot_sensors(kind='3d', ch_type='eeg')

<Figure size 1280x1280 with 1 Axes>

## Select only a subset of the channels

In [11]:
raw.info

<Info | 10 non-empty values
 bads: []
 ch_names: Fp1, AF7, AF3, F1, F3, F5, F7, FT7, FC5, FC3, FC1, C1, C3, C5, ...
 chs: 64 EEG, 4 EOG, 1 Stimulus
 custom_ref_applied: False
 file_id: 4 items (dict)
 highpass: 0.0 Hz
 lowpass: 417.0 Hz
 meas_date: 2015-02-02 17:06:12 UTC
 meas_id: 4 items (dict)
 nchan: 69
 projs: Average EEG reference: off
 sfreq: 512.0 Hz
>

In [23]:
raw_eeg_cropped = raw.copy().crop(tmax=100)
raw_eeg_cropped.times[-1]

100.0

In [24]:
raw_eeg_cropped_filtered = raw_eeg_cropped.filter(l_freq=0.1, h_freq=40)

Filtering raw data in 1 contiguous segment
Setting up band-pass filter from 0.1 - 40 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 0.10
- Lower transition bandwidth: 0.10 Hz (-6 dB cutoff frequency: 0.05 Hz)
- Upper passband edge: 40.00 Hz
- Upper transition bandwidth: 10.00 Hz (-6 dB cutoff frequency: 45.00 Hz)
- Filter length: 16897 samples (33.002 sec)



In [25]:
raw_eeg_cropped.load_data()
raw_eeg_cropped_filtered = raw_eeg_cropped.copy().filter(l_freq=0.1, h_freq=40)

Filtering raw data in 1 contiguous segment
Setting up band-pass filter from 0.1 - 40 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 0.10
- Lower transition bandwidth: 0.10 Hz (-6 dB cutoff frequency: 0.05 Hz)
- Upper passband edge: 40.00 Hz
- Upper transition bandwidth: 10.00 Hz (-6 dB cutoff frequency: 45.00 Hz)
- Filter length: 16897 samples (33.002 sec)



In [1]:
raw_eeg_cropped.plot(events=events)
raw_eeg_cropped_filtered.plot(events=events)

NameError: name 'raw_eeg_cropped' is not defined

In [16]:
print(len(raw_eeg_cropped[68])) # 0~68 channels

2


In [26]:
for i in raw_eeg_cropped_filtered[1][1]:  # x: time
  print(i)
# print(raw_eeg_cropped[0][0][])

0.0
0.001953125
0.00390625
0.005859375
0.0078125
0.009765625
0.01171875
0.013671875
0.015625
0.017578125
0.01953125
0.021484375
0.0234375
0.025390625
0.02734375
0.029296875
0.03125
0.033203125
0.03515625
0.037109375
0.0390625
0.041015625
0.04296875
0.044921875
0.046875
0.048828125
0.05078125
0.052734375
0.0546875
0.056640625
0.05859375
0.060546875
0.0625
0.064453125
0.06640625
0.068359375
0.0703125
0.072265625
0.07421875
0.076171875
0.078125
0.080078125
0.08203125
0.083984375
0.0859375
0.087890625
0.08984375
0.091796875
0.09375
0.095703125
0.09765625
0.099609375
0.1015625
0.103515625
0.10546875
0.107421875
0.109375
0.111328125
0.11328125
0.115234375
0.1171875
0.119140625
0.12109375
0.123046875
0.125
0.126953125
0.12890625
0.130859375
0.1328125
0.134765625
0.13671875
0.138671875
0.140625
0.142578125
0.14453125
0.146484375
0.1484375
0.150390625
0.15234375
0.154296875
0.15625
0.158203125
0.16015625
0.162109375
0.1640625
0.166015625
0.16796875
0.169921875
0.171875
0.173828125
0.17578125
0.

In [27]:
# print(sum(raw_eeg_cropped[0][0][0]) / len(raw_eeg_cropped[0][0][0]))
for i in raw_eeg_cropped_filtered[0][0][0]:  # y 
  print(i)
# print(raw_eeg_cropped[0][0][])

-4.235164736271502e-22
-1.819127286468015e-06
-3.292569418746809e-06
-4.158471868407813e-06
-4.301911710670039e-06
-3.781697901079097e-06
-2.8143299290136448e-06
-1.7192195790973008e-06
-8.38882244816345e-07
-4.539677655891102e-07
-7.142011755665964e-07
-1.6022506718174772e-06
-2.9392566804041524e-06
-4.43032840240474e-06
-5.738350638904591e-06
-6.5674291423628546e-06
-6.73499178048487e-06
-6.214514730775204e-06
-5.138308736779972e-06
-3.7599065563247497e-06
-2.385799619899822e-06
-1.2940278306684659e-06
-6.604826777095176e-07
-5.118963479246268e-07
-7.178209845033652e-07
-1.0241069076892697e-06
-1.1198996542046862e-06
-7.216126616690384e-07
3.471614180651299e-07
2.100127195749184e-06
4.37169291664304e-06
6.84439787721117e-06
9.114649822363641e-06
1.0781553509977682e-05
1.1537759753084709e-05
1.1240522876340635e-05
9.945735698598886e-06
7.896531233186911e-06
5.468953228383684e-06
3.0875467290413505e-06
1.1309772310673005e-06
-1.4983668954539502e-07
-6.816839962689534e-07
-5.75538182159

In [36]:
epochs = mne.Epochs(raw_eeg_cropped_filtered, events, tmin=-0.3, tmax=0.7,
                    preload=True)
fig = epochs.plot(events=events)

Not setting metadata
Not setting metadata
540 matching events found
Setting baseline interval to [-0.30078125, 0.0] sec
Applying baseline correction (mode: mean)
1 projection items activated
Loading data for 540 events and 513 original time points ...
526 bad epochs dropped
You seem to have overlapping epochs. Some event lines may be duplicated in the plot.


/var/folders/_8/02y2g2xx6h10bpqj769kzskm0000gn/T/ipykernel_3802/1400421585.py:3: RuntimeWarning: More events than default colors available. You should pass a list of unique colors.
  fig = epochs.plot(events=events)
/opt/anaconda3/envs/cogs189/lib/python3.10/site-packages/mne/viz/_mpl_figure.py:1779: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  _cols = np.array([self.mne.epoch_color_bad,


In [41]:
print(epochs)

<Epochs |  14 events (all good), -0.300781 - 0.699219 sec, baseline -0.300781 – 0 sec, ~3.9 MB, data loaded,
 '1000': 6
 '11': 0
 '111': 0
 '1111': 2
 '112': 0
 '113': 0
 '114': 0
 '12': 0
 '121': 1
 '122': 1
 '123': 1
 '124': 0
 '13': 0
 '131': 0
 '132': 0
 '133': 0
 '134': 0
 '14': 0
 '141': 0
 '142': 0
 '143': 0
 '144': 0
 '2000': 0
 '2001': 0
 '21': 0
 '211': 0
 '212': 0
 '213': 0
 '214': 0
 '22': 0
 '221': 0
 '222': 0
 '223': 0
 '224': 0
 '23': 0
 '231': 0
 '232': 0
 '233': 0
 '234': 0
 '24': 0
 '241': 0
 '242': 0
 '243': 0
 '244': 0
 '31': 1
 '32': 1
 '33': 1
 '34': 0
 '41': 0
 '42': 0
 '43': 0
 '44': 0>


In [48]:
reject_criteria = dict(eeg=100e-6,  # 100 µV
                       eog=200e-6)  # 200 µV
_ = epochs.drop_bad(reject=reject_criteria)

    Rejecting  epoch based on EEG : ['Fp1', 'AF7', 'AF3', 'Fpz', 'Fp2', 'AF8', 'AF4', 'AFz']
    Rejecting  epoch based on EEG : ['Fp1', 'AF7', 'AF3', 'Fpz', 'Fp2', 'AF8', 'AF4', 'AFz']
    Rejecting  epoch based on EEG : ['P7', 'Fp2']
    Rejecting  epoch based on EEG : ['P7']
    Rejecting  epoch based on EEG : ['Fp1', 'AF7', 'AF3', 'F1', 'Fpz', 'Fp2', 'AF8', 'AF4', 'AFz', 'Fz', 'F2', 'F4', 'F6', 'F8']
    Rejecting  epoch based on EEG : ['Fp1', 'AF7', 'AF3', 'F3', 'F5', 'F7', 'FT7', 'Fpz', 'Fp2', 'AF8', 'AF4', 'AFz', 'Fz', 'F2', 'F4', 'F6', 'F8', 'FT8', 'FC6']
    Rejecting  epoch based on EEG : ['Fp1', 'AF7', 'AF3', 'Fpz', 'Fp2', 'AF8', 'AF4', 'AFz', 'F8']
    Rejecting  epoch based on EEG : ['Fp1', 'AF7', 'AF3', 'Fpz', 'Fp2', 'AF8', 'AF4', 'AFz', 'F8']
    Rejecting  epoch based on EEG : ['Fp1', 'Fpz', 'Fp2', 'AF8']
    Rejecting  epoch based on EEG : ['Fp1', 'AF7', 'AF3', 'F5', 'F7', 'Fpz', 'Fp2', 'AF8', 'AF4', 'AFz', 'F8']
    Rejecting  epoch based on EEG : ['Fp1', 'AF7', 'AF3'

In [50]:
l_aud = epochs[0].average()
l_vis = epochs[2].average()

Removing projector <Projection | Average EEG reference, active : True, n_channels : 64>
Removing projector <Projection | Average EEG reference, active : True, n_channels : 64>


In [51]:
fig1 = l_aud.plot()
fig2 = l_vis.plot(spatial_colors=True)


/opt/anaconda3/envs/cogs189/lib/python3.10/site-packages/mne/utils/check.py:92: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  LooseVersion(library.__version__) < LooseVersion(min_version):
/opt/anaconda3/envs/cogs189/lib/python3.10/site-packages/mne/utils/check.py:92: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  LooseVersion(library.__version__) < LooseVersion(min_version):
QCoreApplication::exec: The event loop is already running
/opt/anaconda3/envs/cogs189/lib/python3.10/site-packages/numpy/lib/function_base.py:495: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/opt/anaconda3/envs/cogs189/lib/python3.10/site-packages/numpy/core/_methods.py:181: RuntimeWarning: invalid value encountered in true_divide
  ret = um.true_divide(
/opt/anaconda3/envs/cogs189/lib/python3.10/site-packages/mne/utils/check.py:92: DeprecationWarning: distutils Version classes are deprecated. Use packagi

KeyboardInterrupt: 

In [52]:
l_aud.plot_topomap(times=[-0.2, 0.1, 0.4], average=0.05)

<MNEFigure size 1200x440 with 4 Axes>

In [53]:
l_aud.plot_joint()

No projector specified for this dataset. Please consider the method self.add_proj.


<Figure size 1918x1028 with 7 Axes>